#!/bin/bash

dir="./src/components/$1"
mkdir $dir
mkdir "$dir/stories"

echo "import React from \"react\";
import { storiesOf } from \"@storybook/react\";
import $1 from \"../$1\";

storiesOf(\"$1\", module)
    .add(\"without props\", () => <$1 />)" >> "$dir/stories/$1.stories.js"

echo "import React, { Component } from \"react\";
import PropTypes from \"prop-types\";
import styles from \"./$1.scss\";

export default class $1 extends Component {
    render() {
        return null;
    }
}" >> "$dir/$1.jsx"

echo ":local {}" >> "$dir/$1.scss"

echo "import $1 from \"./$1.jsx\";
export default $1;" >> "$dir/index.js"